#!/bin/sh
exec rsync -aAXHvh --delete \
  --exclude=/.config/alacritty \
  --exclude=/.config/mako \
  --exclude=/.config/spotify \
  --exclude=/.config/sway \
  --exclude=/.config/waybar \
  --exclude=/.config/wofi \
  --exclude=/.local/state \
  --exclude=/.zcompdump \
  ~/ laptop:~/
