#!/bin/sh

set -e

SWAYSOCK=$(find "${XDG_RUNTIME_DIR:?}" -maxdepth 1 -type s -name "sway*" -print -quit)
export SWAYSOCK

cmd() {
  # https://github.com/swaywm/sway/issues/5931
  swaymsg exec -- "$@"
}

case $1 in
  p | pause | play)
    cmd playerctl play-pause
    ;;
  n | next)
    cmd playerctl next
    ;;
  b | prev)
    cmd playerctl previous
    ;;
  m | mute)
    cmd pactl set-sink-mute @DEFAULT_SINK@ toggle
    ;;
  u | up)
    cmd pactl set-sink-volume @DEFAULT_SINK@ +5%
    ;;
  d | down)
    cmd pactl set-sink-volume @DEFAULT_SINK@ -5%
    ;;
  s | shell)
    exec "${SHELL:?}"
    ;;
  x | exec)
    shift
    cmd "$@"
    ;;
  k | kill)
    swaymsg kill
    ;;
  *)
    printf "unknown command\n" >&2
    exit 1
    ;;
esac
