#!/bin/sh

set -e

name=$(swaymsg -t get_outputs | jq -r '.[] | select( .focused ) | .name')
[ -n "$name" ]

mode=$(
  swaymsg -t get_outputs |
    jq -r '.[] | select( .focused ) | .modes[] |
    ( .width | tostring ) + "x" + ( .height | tostring ) + "@" + ( .refresh | tostring ) + "Hz"' |
    tofi
)
[ -n "$mode" ]

zoom=$(seq 4 | tofi)
[ -n "$zoom" ]

sync=$(printf '%s\n%s\n' off on | tofi)
[ -n "$sync" ]

card=$(pactl -f json list sinks | jq -r '.[] | .name' | tofi)
[ -n "$card" ]

swaymsg output "$name" mode "$mode" scale "$zoom" adaptive_sync "$sync"
pactl set-default-sink "$card"
