#!/bin/sh

set -e

name=$(swaymsg -t get_outputs | jq -r '.[] | select( .focused ) | .name')
[ -n "$name" ]

mode=$(
  swaymsg -t get_outputs |
    jq -r '.[] | select( .focused ) | .modes[] |
    ( .width | tostring ) + "x" + ( .height | tostring ) + "@" + ( .refresh | tostring ) + "Hz"' |
    tofi
)
[ -n "$mode" ]

size=$(seq 4 | tofi)
[ -n "$size" ]

card=$(pactl -f json list sinks | jq -r '.[] | .name' | tofi)
[ -n "$card" ]

swaymsg output "$name" res "$mode"
swaymsg output "$name" scale "$size"
pactl set-default-sink "$card"
