#!/bin/sh

set -e

[ ! -e /tmp/overlay ]
[ ! -e /tmp/upper ]
[ ! -e /tmp/work ]

install -d -m 700 -o cameron -g cameron \
  /tmp/overlay \
  /tmp/upper \
  /tmp/work

mount -t overlay overlay -o nosuid,nodev,noexec,noatime \
  -o lowerdir=/home/cameron \
  -o upperdir=/tmp/upper \
  -o workdir=/tmp/work \
  /tmp/overlay

touch -r /home/cameron /tmp/overlay
