#!/bin/sh

OUTPUT=$(swaymsg -t get_outputs | jq -re '[.[].name][-1]')
ret=$?

if [ $ret -eq 0 ] && [ "$OUTPUT" != eDP-1 ]; then
  swaymsg output "$OUTPUT" mode 1920x1080@60Hz # cap

  swaymsg workspace 2 output "$OUTPUT"

  swaymsg workspace 1 output eDP-1
fi

SPEAKER=$(pactl -f json list sinks | jq -re '[.[].index][-1]')
ret=$?

if [ $ret -eq 0 ]; then
  pactl set-default-sink "$SPEAKER"
else
  pactl set-default-sink 0
fi
