flush ruleset

table inet filter {
  chain input {
    type filter hook input priority 0
    policy drop

    ct state established,related accept
    ct state invalid drop

    iif lo accept

    iifname wg0 goto {
      tcp dport 22 accept

      ip protocol icmp accept
      ip6 nexthdr icmpv6 accept
    }

    udp dport 51820 accept
  }
}
