#!/bin/sh

set -e

TMP="${XDG_RUNTIME_DIR:-/tmp}/.cache"

if [ -z "$HOME" ]; then
  HOME=$(getent passwd "$(id -un)" | cut -d : -f 6)
fi

XDG_CACHE_HOME="$HOME/.cache"

if [ -L "$XDG_CACHE_HOME" ]; then
  unlink "$XDG_CACHE_HOME"
fi

if [ -e "$TMP" ]; then
  rm -rf "$TMP"
fi
