[window.dimensions]
columns = 80
lines = 25

[font]
size = 12

[env]
TERM = "xterm-256color"

[colors.primary]
background = "0x32302f"
foreground = "0xdfbf8e"

[colors.selection]
background = "0x89b482"
text = "0xdfbf8e"

[colors.normal]
black = "0x665c54"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe78a4e"

[colors.bright]
black = "0x928374"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe3a84e"
